#!/bin/bash

c=`ps xau |grep xinit |grep -v grep |wc -l`
if [ "$c"  -ne "0" ]
then
	nvidia-smi
	echo
	echo
	echo auto gpu fan speed is in progress!!!!!
	echo if you want to stop it please use -- sudo reboot -- to restart the host
	echo
	echo
	echo
	exit 1
fi
touch  /tmp/.startoverclock
